### ISSUE TITLE
Open clickgui in main menu

### ISSUE THREAD

**Issue by Calemplayzs** [Hqrion-Clientz/Phobos-1.9.0-BUILDABLE-SRC#23]
When I enable some modules and restart game and try to join server or single player world it gets stuck on loading terrain and I can't find what I enabled and I have to manually disable modules in the config until I find what one it was and it would be nice to have clickgui in main menu for this reason.

**Comment by Hqrion** [comment]
I'm not phobos dev so im not gonna add it sorry
